using System;
using System.Collection.Generic;

class Driver {
	static string TypeToSigType (char c) {
		switch (c) {
		case 'V': return "void";
		case 'I': return "int";
		case 'L': return "gint64";
		case 'F': return "float";
		case 'D': return "double";
		default:
			throw new Exception ("Can't handle " + c);
		}
	}

	const int DEFAULT_INSTANCES = 10;
	static Dictionary<string, int> cookies = new Dictionary<> ();
	/* Cookie description: first char is return type */
	static {
		cookies.Add ("V", DEFAULT_INSTANCES);
		cookies.Add ("VII", DEFAULT_INSTANCES);
	}

	public static void Main () {
		Console.WriteLine ("/*");
		Console.WriteLine ("* DON'T EDIT THIS FILE");
		Console.WriteLine ("* This file was generated by n2m-gen.cs - use it instead.");
		Console.WriteLine ("*/");

		foreach (var entry in cookies) {
			string cookie = entry.Key;
			int instances = cookies [cookie];


		}
		
	}
}
